### ISSUE TITLE
Failure to parse ip address in offer returned from Chrome

### ISSUE THREAD

**Issue by hcl337** [aiortc/aioice#13]
In doing local testing for setting up a WebRTC channel with a simple JS example on the same computer (mac chrome simple JS offer/answer video  + aiortc responding with an image), a python exception is happening on one of our dev computers (because of the browser offer returning what Python thinks is a non-parsable ipv6 address) but not on all of them.

The ice candidates that Chrome returned are:

```
a=candidate:706387448 1 udp 2113937151 5177eebd-d4eb-495a-a75e-0defface8929.local 52832 typ host generation 0 network-cost 999
a=candidate:842163049 1 udp 1677729535 73.170.4.228 52832 typ srflx raddr 0.0.0.0 rport 0 generation 0 network-cost 999
```

And python3 is returning that it can't parse the ipv6 version of it.

```
Task exception was never retrieved
future: <Task finished coro=<RTCPeerConnection.__connect() done, defined at /usr/local/lib/python3.6/dist-packages/aiortc/rtcpeerconnection.py:776> exception=ValueError("'5177eebd-d4eb-495a-a75e-0defface8929.local' does not appear to be an IPv4 or IPv6 address",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiortc/rtcpeerconnection.py", line 781, in __connect
    await iceTransport.start(self.__remoteIce[transceiver])
  File "/usr/local/lib/python3.6/dist-packages/aiortc/rtcicetransport.py", line 289, in start
    await self._connection.connect()
  File "/usr/local/lib/python3.6/dist-packages/aioice/ice.py", line 361, in connect
    if (protocol.local_candidate.can_pair_with(remote_candidate) and
  File "/usr/local/lib/python3.6/dist-packages/aioice/candidate.py", line 114, in can_pair_with
    b = ipaddress.ip_address(other.host)
  File "/usr/lib/python3.6/ipaddress.py", line 54, in ip_address
    address)
ValueError: '5177eebd-d4eb-495a-a75e-0defface8929.local' does not appear to be an IPv4 or IPv6 address
```

On our other computer, these are the candidates which are returned and it does not have this error:

```
a=candidate:2213748025 1 udp 2122260223 169.254.66.7 61769 typ host generation 0 network-id 3
a=candidate:1940115785 1 udp 2122197247 2600:1700:87d0:3800:a4b1:c744:37d:ebc7 61770 typ host generation 0 network-id 2 network-cost 10
a=candidate:1995739850 1 udp 2122129151 192.168.1.65 65067 typ host generation 0 network-id 1 network-cost 10
a=candidate:2162486046 1 udp 1685921535 162.207.207.120 65067 typ srflx raddr 192.168.1.65 rport 65067 generation 0 network-id 1 network-cost 10
a=candidate:3446727113 1 tcp 1518280447 169.254.66.7 9 typ host tcptype active generation 0 network-id 3
a=candidate:1025519033 1 tcp 1518217471 2600:1700:87d0:3800:a4b1:c744:37d:ebc7 9 typ host tcptype active generation 0 network-id 2 network-cost 10
a=candidate:947351098 1 tcp 1518149375 192.168.1.65 9 typ host tcptype active generation 0 network-id 1 network-cost 10
```

It seems that the ipv6 "*.local" is the issue here for python parsing the return.

**Comment by hcl337** [comment]
Ok. I found that it has just been pushed 19 days ago. Updated the code and verified it now works. `pip3 install --upgrade aiortc` Thanks!!
