### ISSUE TITLE
Meaning of `STUN transaction failed (400 - You cannot use the same channel number with different peer)`

### ISSUE THREAD

**Issue by samiamlabs** [aiortc/aioice#46]
Hi!

I'm occasionally getting a bunch of error messages in my aiortc based application that I don't understand.

```
[webrtc_bridge-1] INFO:aioice.turn:TURN channel bound 16385 ('37.3.111.3', 33340)
[webrtc_bridge-1] ERROR:asyncio:Task exception was never retrieved
[webrtc_bridge-1] future: <Task finished name='Task-1372' coro=<TurnClientMixin.send_data() done, defined at /home/dyno/.local/lib/python3.8/site-packages/aioice/turn.py:241> exception=TransactionFailed(Message(message_method=Method.CHANNEL_BIND, message_class=Class.ERROR, transaction_id=b'\xd1\x9a>\xc5\xfe\xc2\x15e\xd8\x7f\x0b!'))>
[webrtc_bridge-1] Traceback (most recent call last):
[webrtc_bridge-1]   File "/home/dyno/.local/lib/python3.8/site-packages/aioice/turn.py", line 251, in send_data
[webrtc_bridge-1]     await self.channel_bind(channel, addr)
[webrtc_bridge-1]   File "/home/dyno/.local/lib/python3.8/site-packages/aioice/turn.py", line 85, in channel_bind
[webrtc_bridge-1]     await self.request_with_retry(request)
[webrtc_bridge-1]   File "/home/dyno/.local/lib/python3.8/site-packages/aioice/turn.py", line 213, in request_with_retry
[webrtc_bridge-1]     response, addr = await self.request(request)
[webrtc_bridge-1]   File "/home/dyno/.local/lib/python3.8/site-packages/aioice/turn.py", line 200, in request
[webrtc_bridge-1]     return await transaction.run()
[webrtc_bridge-1]   File "/home/dyno/.local/lib/python3.8/site-packages/aioice/stun.py", line 299, in run
[webrtc_bridge-1]     return await self.__future
[webrtc_bridge-1] aioice.stun.TransactionFailed: STUN transaction failed (400 - You cannot use the same channel number with different peer)
[webrtc_bridge-1] INFO:aioice.ice:Connection(2) Check CandidatePair(('172.19.0.2', 35871) -> ('<REPLACED_IP_FOR_CUSTOM_TURN_SERVER>, 58892)) State.IN_PROGRESS -> State.SUCCEEDED
[webrtc_bridge-1] INFO:aioice.ice:Connection(2) ICE completed
[webrtc_bridge-1] ERROR:asyncio:Task exception was never retrieved
[webrtc_bridge-1] future: <Task finished name='Task-1376' coro=<TurnClientMixin.send_data() done, defined at /home/dyno/.local/lib/python3.8/site-packages/aioice/turn.py:241> exception=TransactionFailed(Message(message_method=Method.CHANNEL_BIND, message_class=Class.ERROR, transaction_id=b'2 H\xc6\xb60\rm\x10\x13\x06\x83'))>
[webrtc_bridge-1] Traceback (most recent call last):
[webrtc_bridge-1]   File "/home/dyno/.local/lib/python3.8/site-packages/aioice/turn.py", line 251, in send_data
[webrtc_bridge-1]     await self.channel_bind(channel, addr)
[webrtc_bridge-1]   File "/home/dyno/.local/lib/python3.8/site-packages/aioice/turn.py", line 85, in channel_bind
[webrtc_bridge-1]     await self.request_with_retry(request)
[webrtc_bridge-1]   File "/home/dyno/.local/lib/python3.8/site-packages/aioice/turn.py", line 213, in request_with_retry
[webrtc_bridge-1]     response, addr = await self.request(request)
[webrtc_bridge-1]   File "/home/dyno/.local/lib/python3.8/site-packages/aioice/turn.py", line 200, in request
[webrtc_bridge-1]     return await transaction.run()
[webrtc_bridge-1]   File "/home/dyno/.local/lib/python3.8/site-packages/aioice/stun.py", line 299, in run
[webrtc_bridge-1]     return await self.__future
[webrtc_bridge-1] aioice.stun.TransactionFailed: STUN transaction failed (400 - You cannot use the same channel number with different peer)
[webrtc_bridge-1] INFO:aioice.ice:Connection(0) Consent to send expired
[webrtc_bridge-1] INFO:aioice.turn:TURN allocation deleted ('<REPLACED_IP_FOR_CUSTOM_TURN_SERVER>', 59795)
[webrtc_bridge-1] INFO:aioice.turn:TURN allocation deleted ('<REPLACED_IP_FOR_CUSTOM_TURN_SERVER>', 59795)
[webrtc_bridge-1] ERROR:asyncio:Task exception was never retrieved
[webrtc_bridge-1] future: <Task finished name='Task-2961' coro=<TurnClientMixin.delete() done, defined at /home/dyno/.local/lib/python3.8/site-packages/aioice/turn.py:144> exception=InvalidStateError('invalid state')>
[webrtc_bridge-1] Traceback (most recent call last):
[webrtc_bridge-1]   File "/home/dyno/.local/lib/python3.8/site-packages/aioice/turn.py", line 164, in delete
[webrtc_bridge-1]     self.receiver.connection_lost(None)
[webrtc_bridge-1]   File "/home/dyno/.local/lib/python3.8/site-packages/aioice/ice.py", line 174, in connection_lost
[webrtc_bridge-1]     self.__c[webrtc_bridge-1]
```

I'm mostly concerned about the log: `STUN transaction failed (400 - You cannot use the same channel number with different peer)`.
Both sending video and data over WebRTC seem to work for the most part. Video and data transmission does freeze for a couple of seconds from time to time before it starts working again though. Don't know if that is related.

Is this something I should worry about, or can I safely ignore it?

**Comment by Bob10918** [comment]
I have the same issue, but in my case it is critical and often completely prevents the new peers from connecting.
I think the issue is that the channel numbers used by client is always the same:
`self.channel_number = 0x4000  `   (line 65 in aioice/src/aioice/turn.py)
A quick fix I use is to substitute that line with
`self.channel_number = random.randint(0x4000, 0x4fff)`

Maybe this could be implemented in the project as a commit?

**Comment by jlaine** [comment]
I don't understand this issue, unless I'm mistaken I don't see how the channel number is being reused by a given connection, it *should* be increased for every peer.. unless there is a race condition in `send_data`, as we only increase the channel number after binding completes?

@Bob10918 : no to randomising the channel number, this solves nothing and leads to non-deterministic behaviour

**Comment by shreehari-a** [comment]
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<TurnClientMixin.send_data() done, defined at /home/shreehari/.local/lib/python3.6/site-packages/aioice/turn.py:241> exception=TransactionFailed(Message(message_method=Method.CHANNEL_BIND, message_class=Class.ERROR, transaction_id=b'\xe7i\xe5\xb0\xf5\xf9\x9a,\xbf1\x1c\xd9'),)>
Traceback (most recent call last):
  File "/home/shreehari/.local/lib/python3.6/site-packages/aioice/turn.py", line 251, in send_data
    await self.channel_bind(channel, addr)
  File "/home/shreehari/.local/lib/python3.6/site-packages/aioice/turn.py", line 85, in channel_bind
    await self.request_with_retry(request)
  File "/home/shreehari/.local/lib/python3.6/site-packages/aioice/turn.py", line 213, in request_with_retry
    response, addr = await self.request(request)
  File "/home/shreehari/.local/lib/python3.6/site-packages/aioice/turn.py", line 200, in request
    return await transaction.run()
  File "/home/shreehari/.local/lib/python3.6/site-packages/aioice/stun.py", line 299, in run
    return await self.__future
aioice.stun.TransactionFailed: STUN transaction failed (400 - You cannot use the same channel number with different peer)
DEBUG:aioice.ice:Connection(0) protocol(1) > ('172.20.0.1', 59898) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\\\x06\x9a\xb1\x06/\x1bT\x90\xc9m\xa8')

```
This is bothering me as well. This appears when stun fails to find the candidates and hands the control over to turn. Maybe it has to do something while switching from stun mode to turn mode? would like to hear from you @jlaine

**Comment by jlaine** [comment]
I can confirm that during channel binding there is a race condition which can lead to:

- using the same channel number for different peers
- sending multiple channel bind requests for a single peer

I've put together PR #52 which should solve the issue. Ideally I'd like to make the code a little cleaner, but it should still fix the situation.
